language: csharp  
sudo: required  
dist: trusty  
dotnet: 2.0.0
env:  
  - DOTNETCORE=1
mono:  
  - none
os:  
  - linux
branches:  
  only:
    - master
script:  
  - dotnet restore
  - dotnet build
